name: build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Installing PyPi Dependencies
        run: |
          uv venv
          uv pip install clickgen resvg-py
        continue-on-error: false

      - name: Print clickgen Version
        run: |
          uv run clickgen --version
          uv run ctgen --version

      - name: Build
        run: uv run bash build.sh
